// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoehnqkchwualvqhcnar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZWhucWtjaHd1YWx2cWhjbmFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjgyMDcsImV4cCI6MjA2Mzg0NDIwN30.8pjcVBisflMEXG3b3RpDJ54NhDeCpaoKf6l6x_iHRaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);